name: "check"
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

jobs:
  check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check nix flake
      run: |
        nix flake check

    - name: Check formatting
      run: |
        nix run nixpkgs#nixpkgs-fmt -- --check .

    - name: Build nix
      run: |
        nix build .#darwinConfigurations."MacBook-Pro".system

