vim.keymap.set('n', '<leader>ce', '<cmd>RustLsp expandMacro<Cr>', { buffer = 0, desc = '[e]xpand macro' })
vim.keymap.set('n', '<leader>cc', '<cmd>RustLsp flyCheck<Cr>', { buffer = 0, desc = '[c]heck' })
vim.keymap.set('n', '<leader>ch', '<cmd>RustLsp hover actions<Cr>', { buffer = 0, desc = '[h]over' })
vim.keymap.set('n', '<leader>cx', '<cmd>RustLsp explainError<Cr>', { buffer = 0, desc = 'e[x]plain error' })
vim.keymap.set('n', '<leader>ca', '<cmd>RustLsp codeAction<Cr>', { buffer = 0, desc = '[a]ction' })
vim.keymap.set('n', '<leader>cD', '<cmd>RustLsp renderDiagnostic<Cr>', { buffer = 0, desc = '[D]iagnostic' })
vim.keymap.set('n', '<leader>cR', '<cmd>RustAnalyzer restart<Cr>', { buffer = 0, desc = '[R]estart LSP' })

vim.keymap.set('n', '<leader>dd', '<cmd>RustLsp debuggables<Cr>', { buffer = 0, desc = '[d]ebug' })
vim.keymap.set('n', '<leader>dr', '<cmd>RustLsp runnables<Cr>', { buffer = 0, desc = '[r]unnables' })
